# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Users/M.ALI/Downloads/youtube (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:#2B2E4A;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #93291E, stop:1 #ED213A);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.welcome_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon = QtWidgets.QLabel(self.welcome_page)
        self.icon.setStyleSheet("background-color:none;\n"
"")
        self.icon.setFrameShadow(QtWidgets.QFrame.Plain)
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../../../../../Users/M.ALI/Downloads/youtube (4).png"))
        self.icon.setObjectName("icon")
        self.verticalLayout_3.addWidget(self.icon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title = QtWidgets.QLabel(self.welcome_page)
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color:#FFF;\n"
"background-color:none;\n"
"\n"
"")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_3.addWidget(self.title, 0, QtCore.Qt.AlignVCenter)
        self.btn_c = QtWidgets.QPushButton(self.welcome_page)
        self.btn_c.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_c.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_c.setFont(font)
        self.btn_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_c.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_c.setAutoFillBackground(False)
        self.btn_c.setStyleSheet("#btn_c{\n"
"color:#1E2022;\n"
"border-radius:25px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C9D6DF,stop:0.5  #F0F5F9, stop:1 #F0F5F9);\n"
"}\n"
"#btn_c::hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #F0F5F9,stop:0.5  #F0F5F9, stop:1 #C9D6DF);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.btn_c.setIconSize(QtCore.QSize(20, 20))
        self.btn_c.setAutoDefault(False)
        self.btn_c.setDefault(False)
        self.btn_c.setFlat(False)
        self.btn_c.setObjectName("btn_c")
        self.verticalLayout_3.addWidget(self.btn_c, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.welcome_page)
        self.download_page = QtWidgets.QWidget()
        self.download_page.setObjectName("download_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.download_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_f = QtWidgets.QPushButton(self.download_page)
        self.btn_f.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_f.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NP-B")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_f.setFont(font)
        self.btn_f.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_f.setStyleSheet("#btn_f{\n"
"color:#1E2022;\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C9D6DF,stop:0.5  #F0F5F9, stop:1 #F0F5F9);\n"
"}\n"
"#btn_f::hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #F0F5F9,stop:0.5  #F0F5F9, stop:1 #C9D6DF);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.btn_f.setObjectName("btn_f")
        self.gridLayout.addWidget(self.btn_f, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.link_input = QtWidgets.QLineEdit(self.download_page)
        self.link_input.setMinimumSize(QtCore.QSize(600, 40))
        self.link_input.setMaximumSize(QtCore.QSize(450, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_input.setFont(font)
        self.link_input.setStyleSheet("background-color:#fff;\n"
"border-radius:15px;\n"
"padding:10px;")
        self.link_input.setObjectName("link_input")
        self.gridLayout.addWidget(self.link_input, 2, 0, 1, 1)
        self.path_input = QtWidgets.QLineEdit(self.download_page)
        self.path_input.setMinimumSize(QtCore.QSize(600, 40))
        self.path_input.setMaximumSize(QtCore.QSize(450, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.path_input.setFont(font)
        self.path_input.setStyleSheet("background-color:#fff;\n"
"border-radius:15px;\n"
"padding:10px;")
        self.path_input.setObjectName("path_input")
        self.gridLayout.addWidget(self.path_input, 1, 0, 1, 1)
        self.title_2 = QtWidgets.QLabel(self.download_page)
        self.title_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("background-color:none;\n"
"color:white;")
        self.title_2.setObjectName("title_2")
        self.gridLayout.addWidget(self.title_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_d = QtWidgets.QPushButton(self.download_page)
        self.btn_d.setMinimumSize(QtCore.QSize(300, 50))
        self.btn_d.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_d.setFont(font)
        self.btn_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_d.setStyleSheet("#btn_d{\n"
"color:#1E2022;\n"
"border-radius:25px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C9D6DF,stop:0.5  #F0F5F9, stop:1 #F0F5F9);\n"
"}\n"
"#btn_d::hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #F0F5F9,stop:0.5  #F0F5F9, stop:1 #C9D6DF);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.btn_d.setObjectName("btn_d")
        self.horizontalLayout.addWidget(self.btn_d, 0, QtCore.Qt.AlignLeft)
        self.btn_e = QtWidgets.QPushButton(self.download_page)
        self.btn_e.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_e.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_e.setFont(font)
        self.btn_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_e.setStyleSheet("#btn_e{\n"
"color:#1E2022;\n"
"border-radius:25px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C9D6DF,stop:0.5  #F0F5F9, stop:1 #F0F5F9);\n"
"}\n"
"#btn_e::hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #F0F5F9,stop:0.5  #F0F5F9, stop:1 #C9D6DF);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.btn_e.setObjectName("btn_e")
        self.horizontalLayout.addWidget(self.btn_e, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.download_page)
        self.finished_page = QtWidgets.QWidget()
        self.finished_page.setObjectName("finished_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.finished_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon_3 = QtWidgets.QLabel(self.finished_page)
        self.icon_3.setMaximumSize(QtCore.QSize(200, 200))
        self.icon_3.setStyleSheet("background-color:none")
        self.icon_3.setText("")
        self.icon_3.setPixmap(QtGui.QPixmap("../../../../../Users/M.ALI/Downloads/thank-you (2).png"))
        self.icon_3.setScaledContents(True)
        self.icon_3.setObjectName("icon_3")
        self.verticalLayout.addWidget(self.icon_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.title_3 = QtWidgets.QLabel(self.finished_page)
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(30)
        self.title_3.setFont(font)
        self.title_3.setStyleSheet("background-color:none;\n"
"color:white;")
        self.title_3.setObjectName("title_3")
        self.verticalLayout.addWidget(self.title_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.btn_dg = QtWidgets.QPushButton(self.finished_page)
        self.btn_dg.setMinimumSize(QtCore.QSize(300, 50))
        self.btn_dg.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_dg.setFont(font)
        self.btn_dg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dg.setStyleSheet("#btn_dg{\n"
"color:#1E2022;\n"
"border-radius:25px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C9D6DF,stop:0.5  #F0F5F9, stop:1 #F0F5F9);\n"
"}\n"
"#btn_dg::hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #F0F5F9,stop:0.5  #F0F5F9, stop:1 #C9D6DF);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.btn_dg.setObjectName("btn_dg")
        self.verticalLayout.addWidget(self.btn_dg, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.finished_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.title.setText(_translate("MainWindow", "Welcome To Youtube \n"
" Downloader"))
        self.btn_c.setText(_translate("MainWindow", "Continue"))
        self.btn_f.setText(_translate("MainWindow", "choose folder..."))
        self.link_input.setPlaceholderText(_translate("MainWindow", "Link"))
        self.path_input.setPlaceholderText(_translate("MainWindow", "Path"))
        self.title_2.setText(_translate("MainWindow", "Enter path and Link to download video"))
        self.btn_d.setText(_translate("MainWindow", "Start Download"))
        self.btn_e.setText(_translate("MainWindow", "Exist"))
        self.title_3.setText(_translate("MainWindow", "Thank you for using Youtube Downloader"))
        self.btn_dg.setText(_translate("MainWindow", "Download Again"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
